version: "{build}"
os: Windows Server 2012 R2
branches:
  only:
    - master
test: off
deploy: off

environment:
  ruby_version: "22-x64"

install:
  - appveyor DownloadFile https://atom.io/download/windows -FileName AtomSetup.exe
  - AtomSetup.exe /silent
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%LOCALAPPDATA%\atom\bin;%PATH%
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%

build_script:
  - ruby --version
  - erb --version
  - apm -v
  - apm clean
  - apm install
  - apm test
