conf-file=/opt/homebrew/etc/dnsmasq.d/interfaces.conf
resolv-file=/opt/homebrew/etc/dnsmasq.d/filtering.resolv
log-facility=/opt/homebrew/var/log/dnsmasq/dnsmasq.log
servers-file=/opt/homebrew/etc/dnsmasq.d/dnsmasq.blacklist.txt

#server=/unifi.test/#
#conf-file=/usr/local/etc/dnsmasq.d/interfaces.conf
#resolv-file=/usr/local/etc/dnsmasq.d/filtering.resolv
#log-facility=/usr/local/var/log/dnsmasq/dnsmasq.log
#servers-file=/usr/local/etc/dnsmasq.d/dnsmasq.blacklist.txt

# the below resolves a problem with FireFox being slow
cache-rr=ANY

stop-dns-rebind
rebind-domain-ok=/pi.hole/
rebind-domain-ok=/upstream.diefernweherin.com/
rebind-domain-ok=/unifi.test/
rebind-domain-ok=/login.wifionice.de/
rebind-domain-ok=/iceportal.de/
server=/use-application-dns.net/
address=/.test/127.0.0.1
log-queries
log-debug
group=_uucp
