#!/usr/bin/env -P /usr/local/bin:/opt/homebrew/bin bash

while [ -z "$interface" ]; do
interface=$(route -n get default 2>&- | grep -F interface | tr -d ' ' | cut -d: -f2)
sleep 0.1
done
nameserver=$(ipconfig getoption "$interface" domain_name_server)

if [ -z "$nameserver" ]; then
    nameserver=$(nslookup <<< server | grep -F Default | sed 's/Default server:/nameserver/g')
else
    nameserver="nameserver $nameserver"
fi

PREFIX="$(/usr/bin/env -P /usr/local/bin:/opt/homebrew/bin brew --prefix)"

grep -Fq  "${nameserver:-nameserver 1.1.1.1}"   "$PREFIX/etc/dnsmasq.d/filtering.resolv" || \
    echo "${nameserver:-nameserver 1.1.1.1}" > "$PREFIX/etc/dnsmasq.d/filtering.resolv"

iface_contents=$(ifconfig -l -X 'bridge|lo' | xargs printf "interface=%s\n" | grep -Fve bridge0)
if ! diff -q <(echo "$iface_contents") "$PREFIX/etc/dnsmasq.d/interfaces.conf"; then
  echo "$iface_contents" > "$PREFIX/etc/dnsmasq.d/interfaces.conf"
fi

[ -r "$HOME/.netwatchrc" ] && . "$HOME/.netwatchrc"
