#!/usr/bin/env -P /usr/local/bin:/opt/homebrew/bin bash

while [ -z "$interface" ]; do
interface=$(route -n get default 2>&- | grep -F interface | tr -d ' ' | cut -d: -f2)
sleep 0.1
done
nameserver=$(ipconfig getoption "$interface" domain_name_server)

if [ -z "$nameserver" ]; then
    nameserver=$(nslookup <<< server | grep -F Default | sed 's/Default server:/nameserver/g')
else
    nameserver="nameserver $nameserver"
fi

if [ -d /usr/local/etc ]; then
    PREFIX=/usr/local
else
    PREFIX=/opt/homebrew
fi

grep -Fq  "${nameserver:-nameserver 1.1.1.1}"   $PREFIX/etc/dnsmasq.d/filtering.resolv || \
    echo "${nameserver:-nameserver 1.1.1.1}" > $PREFIX/etc/dnsmasq.d/filtering.resolv

[ -r "$HOME/.netwatchrc" ] && . "$HOME/.netwatchrc"
