#!/usr/local/bin/bash

# includes git-completion.bash
# and brew_bash_completion.sh

if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
fi

source ~/.bash.d/launchctl-completion.bash

complete -C aws_completer aws

set completion-ignore-case on

save_function() {
    local ORIG_FUNC=$(declare -f $1)
    local NEWNAME_FUNC="$2${ORIG_FUNC#$1}"
    eval "$NEWNAME_FUNC"
}

save_function _filedir old_filedir

_filedir() {
    #initialization_code
    if [[ $cur == \~\?* ]]; then
        cur=$(echo "$cur" | command sed -Ee 's/^\~\?/~\//')
    fi
    old_filedir
    #cleanup_code
    echo -n ''
}
