#!/usr/local/bin/bash

# includes git-completion.bash
# and brew_bash_completion.sh

export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

source ~/.bash.d/launchctl-completion.bash

complete -C aws_completer aws

set completion-ignore-case on

# pip bash completion start
_pip_completion() {
    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   PIP_AUTO_COMPLETE=1 $1 2>/dev/null ) )
}
complete -o default -F _pip_completion python3 -m pip
# pip bash completion end

save_function() {
    # shellcheck disable=SC2155
    local ORIG_FUNC=$(declare -f "$1")
    local NEWNAME_FUNC="$2${ORIG_FUNC#$1}"
    eval "$NEWNAME_FUNC"
}

save_function _filedir old_filedir

_filedir() {
    #initialization_code
    if [[ $cur == \~\?* ]]; then
        cur=$(command sed -Ee 's/^\~\?/~\//' <<< "$cur")
    fi
    old_filedir
    #cleanup_code
    echo -n ''
}
