#!/usr/local/bin/bash

if [ "$(uname)" = "Darwin" ]; then

    export HOMEBREW_INSTALL_BADGE=🍷
    export HOMEBREW_AUTO_UPDATE_SECS=86400
    export HOMEBREW_NO_GITHUB_API="Doesn't work anyway"
    export HOMEBREW_NO_INSTALL_CLEANUP="Fuck off"
    export HOMEBREW_NO_ANALYTICS="Fuck off, seriously"
    export HOMEBREW_UPDATE_TO_TAG="Homebrew devs suck"
    # export HOMEBREW_BUILD_FROM_SOURCE="Fuck off, forever"

    function project {
        if [ "$1" = 'size' ]; then
            find . -type f \( -iname '*.h' -o -name '*.m' -o -name '*.pch' \) -print0 | xargs -0 wc -l | sort -nr
        elif [ "$1" = 'build' ]; then
            xcodebuild
        elif [ "$1" = 'info' ]; then
            xcodebuild -list
        fi
    }

    export GOPATH=~/Developer/Go
    export GOROOT=/usr/local/opt/go/libexec
    export PATH=$PATH:$GOPATH/bin
    export PATH=$PATH:$GOROOT/bin
    if [ -f ~/.cargo/env ]; then
        source ~/.cargo/env
    fi
fi
