#!/usr/local/bin/bash

# shellcheck disable=SC2155
export EMACS_SERVER_FILE="${TMPDIR}emacs$(id -u)/server"
export EDITOR="/usr/local/bin/emacsclient -t -s $EMACS_SERVER_FILE"
export GIT_EDITOR="$EDITOR"

alias emacs-save="emacsclient -e '(save-some-buffers t)' -s $EMACS_SERVER_FILE >/dev/null"
alias save-emacs=emacs-save
alias emacs-kill="emacsclient -e '(kill-emacs)' -s $EMACS_SERVER_FILE >/dev/null"
alias kill-emacs=emacs-kill

function emacs {
    if [ $# -eq 0 ]; then
        $EDITOR
    else
        local files=$(sed -Ee "s/(^'|'$)/\"/g" <<< "${@@Q}")
        $EDITOR -e "(mapc #'(lambda (file) (find-file-noselect file t)) '($files))" -e "(find-file \"$1\")"
    fi
}
