#!/usr/local/bin/bash
# shellcheck disable=SC2139

# shellcheck disable=SC2155
export EMACS_SERVER_FILE="${TMPDIR}emacs$(id -u)/server"
export EDITOR="/usr/local/bin/emacsclient -t -s $EMACS_SERVER_FILE"
export GIT_EDITOR="$EDITOR"
alias emacs="$EDITOR"
alias emacs-save="emacsclient -e '(save-some-buffers t)' -s $EMACS_SERVER_FILE >/dev/null"
alias save-emacs=emacs-save
alias emacs-kill="emacsclient -e '(kill-emacs)' -s $EMACS_SERVER_FILE >/dev/null"
alias kill-emacs=emacs-kill

function emacsgive {
    emacsclient -e "(kill-new \"$*\")" -s "$EMACS_SERVER_FILE" >/dev/null
}
alias emacs-give='emacsgive';
alias give-emacs='emacsgive';
