tap "homebrew/core"
tap "phusion/passenger"

mas "Pixelmator", id: 407963104
mas "1Blocker", id: 1107421413
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Keynote", id: 409183694
mas "Reeder", id: 1449412482
mas "1Password", id: 443987910

cask "tower"
cask "firefox-developer-edition"
cask "docker"
cask "sketch"

brew "archey", args: ["HEAD"]
brew "bash-completion@2"
brew "bash-git-prompt"
brew "dnsmasq"
brew "emacs"
brew "fd"
brew "geckodriver"
brew "git"
brew "gnupg"
brew "go"
brew "google-authenticator-libpam"
brew "nmap"
brew "node"
brew "passenger", link: false
brew "phusion/passenger/passenger-enterprise"
brew "pigz"
brew "pinentry-mac"
brew "pngcrush"
brew "postgresql"
brew "rbenv-default-gems"
brew "redis"
brew "ripgrep"
brew "rustup-init"
brew "svgcleaner"
brew "tree"
brew "unrar"
brew "web100clt"
brew "wget"
brew "xz"
brew "yarn"
