server {
    listen 8443 ssl;
    ssl_certificate      /etc/apache2/server.crt;
    ssl_certificate_key  /etc/apache2/server.key;

    server_name heartwork.test;

    root /Users/camdennarzt/Sites/heartwork/public;

    passenger_enabled on;
    passenger_app_env development;
    passenger_preload_bundler on;
}
