server {
    listen 8000;
    server_name testapp.test;

    root /Users/camdennarzt/Developer/Ruby/testapp/public;

    passenger_enabled on;
    passenger_app_env development;
    passenger_preload_bundler on;
}
