default_host_triple = "x86_64-apple-darwin"
default_toolchain = "stable"
version = "12"
profile = "default"

[overrides]
"/Users/camdennarzt/Developer/Rust/hello-rocket" = "nightly-x86_64-apple-darwin"
