version = "12"
default_host_triple = "aarch64-apple-darwin"
default_toolchain = "stable-aarch64-apple-darwin"
profile = "default"

[overrides]
"/Users/camdennarzt/Developer/Rust/hello-rocket" = "nightly-aarch64-apple-darwin"
