#!/bin/bash

set -e

# A hook script to verify what is about to be pushed.  Called by "git push" after it has checked the remote status, but
# before anything has been pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

# Name the arguments:
# declare remote_name="$1"
# declare remote_url="$2"

declare zero="$(git hash-object --stdin </dev/null | tr '[:xdigit:]' '0')"

while read -r local_ref local_oid remote_ref remote_oid; do
	if [ "$local_oid" = "$zero" ];	then
		# Handle delete here
		exit 0
	else
		declare range
		if [ "$remote_oid" = "$zero" ]; then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# This script prevents pushing of commits where the log message includes
		# "WIP" (work in progress) or "don't" or "tmp".
		declare -a flags
		for word in WIP TMP "don't"; do
			flags+=("--grep=$word")
		done
		declare commit=$(git rev-list --max-count=1 --fixed-strings --regexp-ignore-case "${flags[@]}" "$range")
		if test -n "$commit"; then
			echo "Found WIP commit (${commit:0:8}) in $local_ref, not pushing" >&2
			PAGER=cat git log --format=%B -n 1 "$commit" >&2
			exit 1
		fi
	fi
done

exit 0
