#!/bin/sh

# Called by "git commit" with the name of the file that has the commit message,
# followed by the description of the commit message's source.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# The hook's purpose is to edit the commit message file.  If the hook fails with
# a non-zero status, the commit is aborted.

# This removes the "# Please enter the commit message..." placeholder.
sed -e '/^. Please enter the commit message/d' -i.bak "$COMMIT_MSG_FILE"

# This includes the output of "git diff --name-status -r" into the message, just
# before the "git status" output.  It is commented because it doesn't cope with
# --amend or with squashed commits.
# case "$COMMIT_SOURCE,$SHA1" in
#  ,|template,)
#    /usr/bin/perl -i.bak -pe '
#       print "\n" . `git diff --cached --name-status -r`
# 	 if /^#/ && $first++ == 0' "$COMMIT_MSG_FILE" ;;
#  *) ;;
# esac
